### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by denterekhov** [binary-studio-academy/stage-2#29]
Images below are not displayed.
It seems that the relative path to the images is used instead of import.

- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L369
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L534
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L553
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L708
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L721
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L724
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L737
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L791
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L812
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L881
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L882
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L950
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L953
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L987
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L990
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L1004
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L1016
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L1147
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L1244
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L1328
- https://github.com/binary-studio-academy/stage-2/blame/fcf98098927cdde170ba3889a1371fe5a694eb94/src/pages/lectures/express-yourself-with-nodejs/index.mdx?fbclid=IwAR3wP7SvjN7MPEVzyEFWAn6MWluAdQx1bCzN5lC3mpq5vG_-W4nENFTk0IM#L1330

**Comment by alexandrtovmach** [comment]
hey, thanks for an investigation. Will fix it

**Comment by alexandrtovmach** [comment]
Solved. @denterekhov Thanks for help!
