### ISSUE TITLE
Path to the non-existent image

### ISSUE THREAD

**Issue by denterekhov** [binary-studio-academy/stage-2#9]
The second link (https://github.com/binary-studio-academy/stage-2/blame/develop/src/pages/lectures/how-developers-work/index.mdx#L232) contains the path to the non-existent image.

**Comment by volodymyr-kushnir** [comment]
@denterekhov ну окей, хитрий жук, ти а) знайшов репозиторій; б) відкрив мені issue. При тому, що я а) на то розраховував; б) на то надіявся. Very well, thank you! There's a problem with the relative path... image itself actually exists https://binary-studio-academy.github.io/stage-2/assets/images/y-u-no-git.png. I wonder, should we go further with this... Would you be so kind to try and send me a PR to fix this?

**Comment by volodymyr-kushnir** [comment]
@denterekhov писав:
> Привет. Лучше напишу лично чем создам еще один issue на GitHub) Обнаружил, что в настройках gatsby указан pathPrefix: /stage-2, поэтому он не нужен в пути к рисунку (сейчас путь /stage-2/stage-2/... вместо /stage-2/...)

На що я:

> Здарова. Да, я вже побачив то після того як змерджив твій PR і тому я наступним коммітом поправив то.

І https://github.com/binary-studio-academy/stage-2/pull/12.
